Repository shardeum/shardeum, pull requests merged in 2024-08, with the labels that each got.

#121 disable broken tests
  test/autoScaleNet.test.ts.disabled
  test/dataSyncTest.ts.disabled
  test/main.test.ts.disabled
  test/scaleTest.ts.disabled
  test/setup/sync.test.ts.disabled
  test/shardedNetwork.test.ts.disabled
  test/singleShardRotation.test.ts.disabled
  test/ut/src/types/NetworkAccount.test.ts.tempdisable
  test/utils/stringify.test.ts.tempdisable
Labels: Review effort [1-5]: 5

#122 BLUE-189(fix): validatePenaltyTX bug that is causing stuck penalty txs
  src/tx/penalty/transaction.ts
Labels: Review effort [1-5]: 2

#151 GOLD-211: ECDSA Multi-sig feature
  src/config/index.ts
  src/index.ts
  src/setup/helpers.ts
  src/setup/validateTransaction.ts
  src/setup/validateTxnFields.ts
  src/shardeum/shardeumFlags.ts
Labels: Review effort [1-5]: 4
