Repository shardeum/shardeum, pull requests merged in 2024-09, with the labels that each got.

#143 Adding AJV validations for external API request body
  jest.config.js
  package.json
  src/index.ts
  src/types/ajv/Helpers.ts
  src/types/ajv/InjectTxReq.ts
  src/types/ajv/QueryCertReq.ts
  src/types/enum/AJVSchemaEnum.ts
  src/utils/serialization/SchemaHelpers.ts
  src/utils/serialization/VectorBufferStream.ts
  src/utils/serialization/prompt.md
  test/unit/src/types/NetworkAccount.test.ts
  test/unit/src/types/NetworkAccount.test.ts.tempdisable
  test/unit/src/types/ajv/InjectTxReq.test.ts
  test/unit/src/utils/retry.test.ts
Labels: Review effort [1-5]: 3

#161 BLUE-226 Added enableRPCEndpoints config in the network parameters
  src/index.ts
  src/shardeum/initialNetworkParameters.ts
  src/shardeum/shardeumFlags.ts
  src/shardeum/shardeumTypes.ts
Labels: Review effort [1-5]: 3

#160 RED-274: Limit staking to once per 30 minutes
  src/index.ts
  src/shardeum/initialNetworkParameters.ts
  src/shardeum/shardeumConstants.ts
  src/shardeum/shardeumTypes.ts
  src/tx/staking/verifyStake.ts
  src/types/NodeAccount.ts
Labels: Review effort [1-5]: 3

#158 BLUE-228: fix: subtracting slashing penalty twice
  src/index.ts
Labels: Review effort [1-5]: 2

#152 doc: how to add your wallet address to the genesis file
  README.md
Labels: Review effort [1-5]: 1

#166 Fix: ChainId validation to prevent cross chain replay attacks
  src/index.ts
  src/shardeum/shardeumFlags.ts
Labels: Review effort [1-5]: 2

#174 RED-304: Fix restore network caused by early shardus use
  src/setup/sync.ts
Labels: Review effort [1-5]: 2

#182 PM-149 - Clean up patch files that are not used regularly.
  debug-100-nodes.patch
  debug-20-nodes.patch
  debug-300-nodes.patch
  dev_300.patch
  dev_settings.patch
  full-logs.patch
  itn500.patch
  itnPhase1.patch
  itn_settings.patch
  network8080.patch
  network8081.patch
  opoqStage3.patch
  removestuck.patch
  stage1.patch
  stage2.local26.patch
  stage2.patch
  stage3.patch
Labels: Review effort [1-5]: 3

#191 RED-322: check for lost node in cycle record in claimReward beforeAddVerifier
  src/index.ts
Labels: Review effort [1-5]: 2
