Repository shardeum/shardeum, pull requests merged in 2025-03, with the labels that each got.

#390 Added unit tests for src/storage/storage.ts file
  test/unit/src/storage/storage.test.ts
Labels: Review effort 4/5

#395 Fix/reset mocks
  jest.config.js
  src/shardeum/secureAccounts.ts
  test/unit/src/shardeum/networkAccountService.test.ts
  test/unit/src/shardeum/secureAccounts.test.ts
Labels: Review effort 2/5

#391 SHARD-1960: max response size
  scripts/accountsSyncCheck.ts
  src/index.ts
  src/setup/ticket-manager/index.ts
  src/shardeum/services/networkAccountService.ts
  src/utils/customHttpFunctions.ts
  src/utils/requests.ts
  test/unit/src/setup/ticket-manager/ticketTypes.test.ts
  test/unit/src/shardeum/networkAccountService.test.ts
Labels: Review effort 3/5

#397 SHARD-1960: use streams for axios requests as well
  src/utils/customHttpFunctions.ts
  test/unit/src/utils/customHttpFunctions.test.ts
Labels: Review effort 4/5

#387 Unit tests for versioning
  test/unit/src/versioning/types.test.ts
Labels: Review effort 2/5

#386 Unit tests for TypeIdentifierEnum
  test/unit/src/types/enum/TypeIdentifierEnum.test.ts
Labels: Review effort 2/5

#388 feat : add unit tests for EVMAccount serialization and deserialization
  test/unit/src/shardeum/EVMAccount.test.ts
Labels: Review effort 4/5

#392 Added UTs for AJV Helpers file
  test/unit/src/types/ajv/Helpers.test.ts
Labels: Review effort 2/5

#393 Added UTs for queryCertificate.ts
  test/unit/src/handlers/queryCertificate.test.ts
Labels: Review effort 3/5

#401 test : add unit tests for claimReward functionality in Shardeum
  test/unit/src/shardeum/claimReward.test.ts
Labels: Review effort 4/5

#399 test : add unit tests for initRewardTimes functionality
  test/unit/src/shardeum/initRewardTimes.test.ts
Labels: Review effort 4/5

#389 feat : add unit tests for WrappedEVMAccount serialization and deserialization
  test/unit/src/shardeum/WrappedEVMAccount.test.ts
Labels: Review effort 5/5

#413 SHARD-2098 - Update keys.
  src/config/index.ts
Labels: Review effort 2/5

#412 SHARD-2060: revert previous changes to `isInternalTx` to accomodate for internalTxs that are passed in as timestampedTxs
  src/setup/helpers.ts
Labels: Review effort 2/5

#403 test: add unit tests for schema definitions including SQLDataTypes and ColumnDescription
  test/unit/src/storage/utils/schemaDefintions.test.ts
Labels: Review effort 2/5

#414 feat: update permissions list + minSigRequired configs
  src/config/index.ts
  src/config/multisig-permissions.json
Labels: Review effort 3/5

#418 Default some configs.
  src/config/index.ts
Labels: Review effort 1/5

#419 Add hw key for tim
  src/config/index.ts
  src/config/multisig-permissions.json
Labels: Review effort 2/5

#404 test: enhance ClaimRewardTx and NodeRewardTxData schema validation tests
  test/unit/src/types/ajv/ClaimRewardTxSchema.test.ts
Labels: Review effort 2/5

#407 test: add unit tests for JoinAppData schema validation
  test/unit/src/types/ajv/JoinAppData.test.ts
Labels: Review effort 2/5

#408 test: add unit tests for QueryCertReq schema validation
  test/unit/src/types/ajv/QueryCertReq.test.ts
Labels: Review effort 2/5

#402 test: enhance unit tests for keyUtils with comprehensive cases
  test/unit/src/utils/keyUtils.test.ts
Labels: Review effort 2/5

#409 test: add unit tests for Cache class functionality
  test/unit/src/state/cache.test.ts
Labels: Review effort 2/5

#384 feat: add unit tests for wrappedEVMAccountFunctions
  test/unit/src/shardeum/wrappedEVMAccountFunctions.test.ts
Labels: Review effort 4/5

#415 feat: add unit tests for setCertTime
  test/unit/src/tx/setCertTime.test.ts
Labels: Review effort 4/5

#383 add unit tests for `evmAddress.ts`
  test/unit/src/shardeum/evmAddress.test.ts
Labels: Review effort 2/5
