Repository shardeum/shardeum, pull requests merged in 2025-04, with the labels that each got.

#421 SHARD-2128 - fix: chainId inside changeConfig, changenetwork
  scripts/run-env.sh
  src/config/index.ts
  src/config/multisig-permissions.json
  src/setup/validateTransaction.ts
  src/setup/validateTxnFields.ts
  src/shardeum/secureAccounts.ts
  src/shardeum/shardeumTypes.ts
  src/types/ajv/ChangeConfigTxSchema.ts
  src/types/ajv/ChangeNetworkParamTxSchema.ts
  src/utils/multisig.ts
  src/utils/validateChainId.ts
  test/unit/src/types/ajv/ChangeConfigTxSchema.test.ts
  test/unit/src/types/ajv/ChangeNetworkParamTxSchema.test.ts
  test/unit/src/utils/cleanMultiSigPermissions.test.ts
  test/unit/src/utils/cleanMultiSigPermissionsProduction.test.ts
  test/unit/src/utils/multisigIntegration.test.ts
  test/unit/src/utils/nonKeyChangeIntegration.test.ts
  test/unit/src/utils/normalizedAddressHandling.test.ts
  test/unit/src/utils/validateChainId.test.ts
Labels: Review effort 3/5

#424 Add ms keys for testing and make them genesis
  src/config/genesis.json
Labels: Review effort 2/5

#428 fix: pr feedback from tim
  src/utils/validateChainId.ts
  test/unit/src/utils/validateChainId.test.ts
Labels: Review effort 2/5

#429 Make env specific copies of 3 different json files.
  src/config/devnet.genesis-secure-accounts.json
  src/config/devnet.genesis.json
  src/config/devnet.multisig-permissions.json
  src/config/local.genesis-secure-accounts.json
  src/config/local.genesis.json
  src/config/local.multisig-permissions.json
  src/config/mainnet.genesis-secure-accounts.json
  src/config/mainnet.genesis.json
  src/config/mainnet.multisig-permissions.json
  src/config/stagenet.genesis-secure-accounts.json
  src/config/stagenet.genesis.json
  src/config/stagenet.multisig-permissions.json
  src/config/testnet.genesis-secure-accounts.json
  src/config/testnet.genesis.json
  src/config/testnet.multisig-permissions.json
Labels: Review effort 4/5

#423 fix: update secure account addrs for primetime
  src/config/genesis-secure-accounts.json
Labels: Review effort 2/5

#430 SHARD-2159: allow files specified in env vars to set genesis and multisig
  src/setup/sync.ts
  src/setup/validateTxnFields.ts
  src/shardeum/secureAccounts.ts
Labels: Review effort 4/5

#431 SHARD-2172 - Super awesome data pipeline and data.
  .gitignore
  environments/devnet.config.json
  environments/local.config.json
  environments/mainnet.config.json
  environments/stagenet.config.json
  environments/testnet.config.json
  scripts/environmentGeneration/README.md
  scripts/environmentGeneration/package-lock.json
  scripts/environmentGeneration/package.json
  scripts/environmentGeneration/src/generateEnvironment.js
  scripts/environmentGeneration/src/getToken.js
  scripts/environmentGeneration/src/googleSheets.js
  src/config/devnet.genesis-secure-accounts.json
  src/config/devnet.genesis.json
  src/config/devnet.multisig-permissions.json
  src/config/genesis-secure-accounts.json
  src/config/genesis.json
  src/config/local.genesis-secure-accounts.json
  src/config/local.genesis.json
  src/config/local.multisig-permissions.json
  src/config/mainnet.genesis-secure-accounts.json
  src/config/mainnet.genesis.json
  src/config/mainnet.multisig-permissions.json
  src/config/multisig-permissions.json
  src/config/stagenet.genesis-secure-accounts.json
  src/config/stagenet.genesis.json
  src/config/stagenet.multisig-permissions.json
  src/config/testnet.genesis-secure-accounts.json
  src/config/testnet.genesis.json
  src/config/testnet.multisig-permissions.json
Labels: Review effort 5/5

#432 SHARD-2172 - Fixes
  scripts/environmentGeneration/src/generateEnvironment.js
  src/config/devnet.multisig-permissions.json
  src/config/local.multisig-permissions.json
  src/config/mainnet.multisig-permissions.json
  src/config/multisig-permissions.json
  src/config/stagenet.multisig-permissions.json
  src/config/testnet.multisig-permissions.json
Labels: Review effort 2/5

#434 SHARD-2180 - Update data
  environments/devnet.config.json
  environments/local.config.json
  environments/mainnet.config.json
  environments/stagenet.config.json
  environments/testnet.config.json
  scripts/environmentGeneration/src/googleSheets.js
  src/config/devnet.genesis-secure-accounts.json
  src/config/devnet.genesis.json
  src/config/genesis-secure-accounts.json
  src/config/genesis.json
  src/config/local.genesis-secure-accounts.json
  src/config/local.genesis.json
  src/config/mainnet.genesis-secure-accounts.json
  src/config/mainnet.genesis.json
  src/config/mainnet.multisig-permissions.json
  src/config/multisig-permissions.json
  src/config/stagenet.genesis-secure-accounts.json
  src/config/stagenet.genesis.json
  src/config/stagenet.multisig-permissions.json
  src/config/testnet.genesis-secure-accounts.json
  src/config/testnet.genesis.json
Labels: Review effort 2/5

#435 SHARD-2191: fix: if branch for `isRestakingAllowed`
  src/tx/staking/verifyStake.ts
Labels: Review effort 2/5

#437 SHARD-2189 4725-data-import
  environments/mainnet.config.json
  environments/stagenet.config.json
  src/config/devnet.genesis-secure-accounts.json
  src/config/devnet.genesis.json
  src/config/genesis.json
  src/config/local.genesis-secure-accounts.json
  src/config/local.genesis.json
  src/config/mainnet.genesis.json
  src/config/mainnet.multisig-permissions.json
  src/config/multisig-permissions.json
  src/config/stagenet.genesis-secure-accounts.json
  src/config/stagenet.genesis.json
  src/config/stagenet.multisig-permissions.json
  src/config/testnet.genesis-secure-accounts.json
  src/config/testnet.genesis.json
Labels: Review effort 2/5

#438 SHARD-2189 4725-data-import
  environments/mainnet.config.json
  environments/stagenet.config.json
  src/config/devnet.genesis-secure-accounts.json
  src/config/devnet.genesis.json
  src/config/genesis.json
  src/config/local.genesis-secure-accounts.json
  src/config/local.genesis.json
  src/config/mainnet.genesis.json
  src/config/mainnet.multisig-permissions.json
  src/config/multisig-permissions.json
  src/config/stagenet.genesis-secure-accounts.json
  src/config/stagenet.genesis.json
  src/config/stagenet.multisig-permissions.json
  src/config/testnet.genesis-secure-accounts.json
  src/config/testnet.genesis.json
Labels: Review effort 3/5

#439 SHARD-2189 - Data import #2
  environments/mainnet.config.json
  environments/stagenet.config.json
  src/config/genesis-secure-accounts.json
  src/config/genesis.json
  src/config/mainnet.genesis-secure-accounts.json
  src/config/mainnet.genesis.json
  src/config/mainnet.multisig-permissions.json
  src/config/multisig-permissions.json
  src/config/stagenet.genesis-secure-accounts.json
  src/config/stagenet.genesis.json
  src/config/stagenet.multisig-permissions.json
Labels: Review effort 2/5

#440 SHARD-2187: fix receipt for unstake/stake tx to have correct gasUsed/gasPrice values and bring txFee more in line with coinTransfers
  src/index.ts
Labels: Review effort 3/5

#441 mainnet cherry pick
  environments/mainnet.config.json
  environments/stagenet.config.json
  src/config/genesis-secure-accounts.json
  src/config/genesis.json
  src/config/mainnet.genesis-secure-accounts.json
  src/config/mainnet.genesis.json
  src/config/mainnet.multisig-permissions.json
  src/config/multisig-permissions.json
  src/config/stagenet.genesis-secure-accounts.json
  src/config/stagenet.genesis.json
  src/config/stagenet.multisig-permissions.json
  src/index.ts
Labels: Review effort 4/5

#444 SHARD-2203 4825-data-1
  src/config/devnet.genesis-secure-accounts.json
  src/config/devnet.genesis.json
  src/config/genesis-secure-accounts.json
  src/config/genesis.json
  src/config/local.genesis-secure-accounts.json
  src/config/local.genesis.json
  src/config/mainnet.genesis-secure-accounts.json
  src/config/mainnet.genesis.json
  src/config/stagenet.genesis-secure-accounts.json
  src/config/stagenet.genesis.json
  src/config/testnet.genesis-secure-accounts.json
  src/config/testnet.genesis.json
Labels: Review effort 2/5

#445 SHARD-2199: add enableDebugFlags support
  environments/devnet.config.json
  environments/local.config.json
  environments/mainnet.config.json
  environments/stagenet.config.json
  environments/testnet.config.json
  src/config/index.ts
  src/index.ts
Labels: Review effort 2/5

#447 cherry pick main
  environments/devnet.config.json
  environments/local.config.json
  environments/mainnet.config.json
  environments/stagenet.config.json
  environments/testnet.config.json
  package-lock.json
  package.json
  src/config/devnet.genesis-secure-accounts.json
  src/config/devnet.genesis.json
  src/config/genesis-secure-accounts.json
  src/config/genesis.json
  src/config/index.ts
  src/config/local.genesis-secure-accounts.json
  src/config/local.genesis.json
  src/config/mainnet.genesis-secure-accounts.json
  src/config/mainnet.genesis.json
  src/config/stagenet.genesis-secure-accounts.json
  src/config/stagenet.genesis.json
  src/config/testnet.genesis-secure-accounts.json
  src/config/testnet.genesis.json
  src/index.ts
Labels: Review effort 3/5

#448 SHARD-2225: Fix issue with replacing keys in config
  src/config/index.ts
  src/utils/customMerge.ts
  test/unit/utils/customMerges.test.ts
Labels: Review effort 3/5

#450 SHARD-2221 - 2 week cooldown
  src/shardeum/initialNetworkParameters.ts
  src/types/ajv/TransferFromSecureAccountTxSchema.ts
  src/utils/customMerge.ts
  src/utils/validateChainId.ts
  test/unit/src/shardeum/initialNetworkParameters.test.ts
Labels: Review effort 1/5

#451 SHARD-2227 - Data Export
  src/config/devnet.genesis-secure-accounts.json
  src/config/devnet.genesis.json
  src/config/local.genesis-secure-accounts.json
  src/config/local.genesis.json
  src/config/stagenet.genesis-secure-accounts.json
  src/config/stagenet.genesis.json
  src/config/testnet.genesis-secure-accounts.json
  src/config/testnet.genesis.json
Labels: Review effort 2/5

#452 SHARD-2213: network config compare tool
  .gitignore
  scripts/network-account-compare/README.md
  scripts/network-account-compare/package-lock.json
  scripts/network-account-compare/package.json
  scripts/network-account-compare/src/comparator.ts
  scripts/network-account-compare/src/config.ts
  scripts/network-account-compare/src/index.ts
  scripts/network-account-compare/src/types.ts
  scripts/network-account-compare/tsconfig.json
Labels: Review effort 3/5

#453 SHARD-2231 - Disable txn
  environments/devnet.config.json
  environments/local.config.json
  environments/mainnet.config.json
  environments/stagenet.config.json
  environments/testnet.config.json
Labels: Review effort 2/5

#454 SHARD-2232 - Data export
  environments/devnet.config.json
  environments/local.config.json
  environments/mainnet.config.json
  environments/stagenet.config.json
  environments/testnet.config.json
  src/config/genesis-secure-accounts.json
  src/config/genesis.json
  src/config/mainnet.genesis-secure-accounts.json
  src/config/mainnet.genesis.json
  src/config/mainnet.multisig-permissions.json
  src/config/multisig-permissions.json
  src/config/stagenet.genesis.json
  src/config/stagenet.multisig-permissions.json
Labels: Review effort 2/5

#443 SHARD-2193: early return for staking estimates
  src/index.ts
Labels: Review effort 2/5

#457 Dockerfile updates
  .github/workflows/docker-build.yml
  Dockerfile
  dev.Dockerfile
  package.json
Labels: Review effort 2/5

#458 Network restore fixes
  src/index.ts
  src/shardeum/services/networkAccountService.ts
Labels: Review effort 2/5

#461 SHARD-2241 - Update accounts
  src/config/genesis-secure-accounts.json
  src/config/mainnet.genesis-secure-accounts.json
  src/config/stagenet.genesis-secure-accounts.json
Labels: Review effort 2/5

#465 SHARD-2253
  environments/devnet.config.json
  environments/local.config.json
  environments/stagenet.config.json
  environments/testnet.config.json
  src/config/devnet.genesis-secure-accounts.json
  src/config/devnet.genesis.json
  src/config/devnet.multisig-permissions.json
  src/config/genesis-secure-accounts.json
  src/config/genesis.json
  src/config/local.genesis-secure-accounts.json
  src/config/local.genesis.json
  src/config/local.multisig-permissions.json
  src/config/mainnet.genesis-secure-accounts.json
  src/config/mainnet.genesis.json
  src/config/stagenet.genesis-secure-accounts.json
  src/config/stagenet.genesis.json
  src/config/testnet.genesis-secure-accounts.json
  src/config/testnet.genesis.json
  src/config/testnet.multisig-permissions.json
Labels: Review effort 2/5

#459 SHARD-2216 : Attack vector 3 - shard 2236
  src/debug/utils/wrappedEVMAccountFunctions.ts
  src/shardeum/wrappedEVMAccountFunctions.ts
  test/unit/src/shardeum/wrappedEVMAccountFunctions.test.ts
Labels: Review effort 2/5

#474 SHARD-2299 - Update Json
  environments/devnet.config.json
  environments/local.config.json
  environments/stagenet.config.json
  environments/testnet.config.json
  src/config/devnet.genesis-secure-accounts.json
  src/config/devnet.genesis.json
  src/config/devnet.multisig-permissions.json
  src/config/local.genesis-secure-accounts.json
  src/config/local.genesis.json
  src/config/local.multisig-permissions.json
  src/config/stagenet.genesis-secure-accounts.json
  src/config/stagenet.genesis.json
  src/config/stagenet.multisig-permissions.json
  src/config/testnet.genesis-secure-accounts.json
  src/config/testnet.genesis.json
  src/config/testnet.multisig-permissions.json
Labels: Review effort 2/5

#475 SHARD-2304: Check node state when call canUnstake endpoint
  src/index.ts
  src/tx/staking/verifyStake.ts
Labels: Review effort 3/5

#476 SHARD-2275 : add debug endpoints for core flags
  package-lock.json
  package.json
  src/index.ts
Labels: Review effort 3/5

#481 SHARD-2312: Check certExp time in isStakeUnlocked check
  src/tx/staking/verifyStake.ts
  test/unit/src/shardeum/initialNetworkParameters.test.ts
Labels: Review effort 2/5

#479 SHARD-2304: Fix re-stake reason msg
  src/tx/staking/verifyStake.ts
Labels: Review effort 1/5
