Repository shardeum/shardeum, pull requests merged in 2025-07, with the labels that each got.

#558 SHARD-2544 - added error handling for floating promises at imp places only
  src/index.ts
  src/utils/promises.ts
Labels: Review effort 2/5

#561 fix issue in blake2f precompile
  jest.config.js
  src/evm_v2/precompiles/09-blake2f.ts
  test/testCases/transactionPoC.test.ts
  test/unit/src/shardeum/shardeumFlags.test.ts
Labels: Review effort 2/5

#565 added ai sec review to ci step
  .github/workflows/security-review.yml
Labels: Review effort 4/5

#570 Merge smart contracts to dev
  jest.config.js
  src/config/index.ts
  src/evm_v2/evm.ts
  src/evm_v2/interfaces.ts
  src/evm_v2/interpreter.ts
  src/evm_v2/journal.ts
  src/evm_v2/opcodes/functions.ts
  src/evm_v2/precompiles/09-blake2f.ts
  src/evm_v2/types.ts
  src/index.ts
  src/setup/sync.ts
  src/setup/validateTxnFields.ts
  src/shardeum/initialNetworkParameters.ts
  src/shardeum/secureAccounts.ts
  src/shardeum/shardeumFlags.ts
  src/shardeum/shardeumTypes.ts
  src/state/shardeumState.ts
  src/state/transactionState.ts
  src/vm_v7/runTx.ts
  test/testCases/transactionPoC.test.ts
  test/unit/src/shardeum/claimReward.test.ts
  test/unit/src/shardeum/initRewardTimes.test.ts
  test/unit/src/shardeum/networkAccounts.test.ts
  test/unit/src/shardeum/shardeumConfig.test.ts
  test/unit/src/shardeum/shardeumFlags.test.ts
  test/unit/src/shardeum/shardeumTypes.test.ts
  test/unit/src/state/shardeumState.test.ts
  test/unit/src/state/transactionState.test.ts
  test/unit/src/utils/general.test.ts
Labels: Review effort 5/5

#566 Enhance initRewardTimes validation
  src/tx/initRewardTimes.ts
  test/unit/src/shardeum/initRewardTimes.test.ts
  test/unit/src/shardeum/initRewardValidateTx.test.ts
Labels: Review effort 3/5

#571 SHARD-2647: Add nodeRewardCap config and implement node reward limit using the same
  scripts/network-account-compare/src/types.ts
  src/debug/evmSetup/index.ts
  src/shardeum/initialNetworkParameters.ts
  src/shardeum/shardeumTypes.ts
  src/tx/claimReward.ts
  test/unit/src/shardeum/claimReward.test.ts
  test/unit/src/shardeum/initRewardTimes.test.ts
  test/unit/src/shardeum/networkAccounts.test.ts
  test/unit/src/shardeum/shardeumTypes.test.ts
  test/unit/src/utils/general.test.ts
Labels: Review effort 4/5

#578 upgrade node
  package-lock.json
  package.json
Labels: Review effort 1/5

#573 out of bound write - fix in bloom
  src/vm_v7/bloom/index.ts
Labels: Review effort 2/5

#575 SHARD-2673: Disable the 100 bonus SHM when in debug mode.
  src/debug/estimateGas/estimateGas.ts
  src/index.ts
  src/setup/sync.ts
  src/shardeum/shardeumFlags.ts
  test/unit/src/shardeum/shardeumFlags.test.ts
Labels: Review effort 2/5

#576 SHARD-2667: Improve gas estimation
  src/index.ts
  src/utils/transaction.ts
Labels: Review effort 4/5

#583 fixed dockerfile for node 20
  Dockerfile
Labels: Review effort 2/5

#574 SHARD-2656: Improve EVM execution revert messages
  src/index.ts
Labels: Review effort 4/5

#582 Shard 2630
  src/index.ts
  src/tx/claimReward.ts
  src/tx/initRewardTimes.ts
  test/unit/src/shardeum/claimReward.test.ts
  test/unit/src/shardeum/initRewardTimes.test.ts
  test/unit/src/shardeum/initRewardValidateTx.test.ts
  test/unit/src/shardeum/rewardSystemSecurity.test.ts
Labels: Review effort 3/5
