Repository shardeum/shardeum, pull requests merged in 2025-05, with the labels that each got.

#484 Cherry pick hotfix to dev branch
  package-lock.json
  package.json
  src/config/index.ts
  src/index.ts
  src/tx/staking/verifyStake.ts
  test/unit/src/shardeum/initialNetworkParameters.test.ts
Labels: Review effort 3/5

#491 Update keys to match network
  environments/mainnet.config.json
Labels: Review effort 1/5

#489 Correct wrongly named key
  src/utils/multisig.ts
Labels: Review effort 1/5

#495 SHARD-2448: Implement getUniqueAppTags
  src/index.ts
Labels: Review effort 2/5

#497 SHARD-2455 - Adjust testnet genesis config for reset
  environments/testnet.config.json
Labels: Review effort 2/5

#544 SHARD-2464 - Update configs.
  environments/devnet.config.json
  environments/local.config.json
  environments/mainnet.config.json
  environments/stagenet.config.json
  environments/testnet.config.json
  src/config/devnet.genesis-secure-accounts.json
  src/config/devnet.genesis.json
  src/config/devnet.multisig-permissions.json
  src/config/genesis.json
  src/config/local.genesis-secure-accounts.json
  src/config/local.genesis.json
  src/config/local.multisig-permissions.json
  src/config/mainnet.genesis.json
  src/config/mainnet.multisig-permissions.json
  src/config/multisig-permissions.json
  src/config/stagenet.genesis-secure-accounts.json
  src/config/stagenet.genesis.json
  src/config/stagenet.multisig-permissions.json
  src/config/testnet.genesis-secure-accounts.json
  src/config/testnet.genesis.json
  src/config/testnet.multisig-permissions.json
Labels: Review effort 2/5

#546 set flexibleRotationDelta to 0 for testnet
  environments/testnet.config.json
Labels: Review effort 1/5
